%YAML:1.0
---
image_width: 640
image_height: 480

camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: f
   data: [607.03516, 0., 322.11072,
          0., 607.06201, 240.75599,
          0., 0., 1.]

distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: f
   data: [0., 0., 0., 0., 0.]